<?php

namespace App;

use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Customer extends Model
{
    protected $fillable = [
        'name',
        'lastname',
        'phone',
        'address',
        'city',
        'IsLegalEntity',
        'legalEntity_id'
    ];

//    protected static function boot()
//    {
//        parent::boot(); // TODO: Change the autogenerated stub
//
//        self::creating(function ($model) {
//            return $model->id;
//        });
//    }

    public function companies()
    {
        return $this->hasMany(Company::class);
    }

    public function assets()
    {
        return $this->hasMany(Asset::class);
    }

    public function sendEmailReminder(Schedule $schedule)
    {
//        $schedule->command()
    }
}
